import "oaidl.idl";
import "ocidl.idl";
import "IImage3d.idl";


[
    version(2.0),
    uuid(ED4540BD-07B5-44B0-BCDE-3E2C1D99183B),
    helpstring("DummyLoader module")
]
library DummyLoader
{
    importlib("stdole2.tlb");

    [
        version(2.0),
        uuid(50BE330D-F729-4D8F-A1E4-C939E0598EDF),
        helpstring("3D image source")
    ]
    coclass Image3dSource
    {
        [default] interface IImage3dSource;
    };

    [
        version(2.0),
        uuid(1326A2C6-7753-4584-B866-CDF3C6E240F1),
        helpstring("3D image file loader")
    ]
    coclass Image3dFileLoader
    {
        [default] interface IImage3dFileLoader;
    };

};
