import "oaidl.idl";
import "ocidl.idl";
import "IImage3d.idl";


[
    version(1.2),
    uuid(67E59584-3F6A-4852-8051-103A4583CA5E),
    helpstring("DummyLoader module")
]
library DummyLoader
{
    importlib("stdole2.tlb");

    [
        version(1.2),
        uuid(78317A0E-56BF-4735-AB5B-FE0751219FE8),
        helpstring("3D image stream")
    ]
    coclass Image3dStream
    {
        [default] interface IImage3dStream;
    };

    [
        version(1.2),
        uuid(6FA82ED5-6332-4344-8417-DEA55E72098C),
        helpstring("3D image source")
    ]
    coclass Image3dSource
    {
        [default] interface IImage3dSource;
    };

    [
        version(1.2),
        uuid(8E754A72-0067-462B-9267-E84AF84828F1),
        helpstring("3D image file loader")
    ]
    coclass Image3dFileLoader
    {
        [default] interface IImage3dFileLoader;
    };

};
