/* IImage3dTypeLibraryGenerator.idl
*  Generates a type library file for IImage3d.idl for use in interface implementation
*/


import "oaidl.idl";
import "IImage3d.idl";


[
    uuid(3ff1aab8-f3d8-33d4-825d-00104b3646c0),
    helpstring("Interface to generate IImage3dAPI.tlb .")
]
library Image3dlib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    enum      Image3dAPIVersion;
    interface IImage3dFileLoader;
};
