/* IImage3dTypeLibraryGenerator.idl
*  Generates a type library file for IImage3d.idl for use in interface implementation
*/


import "oaidl.idl";
import "IImage3d.idl";


[
    uuid(1979020F-3402-49AD-A17C-507A1BBE4D09),
    helpstring("Interface to generate IImage3dAPI.tlb .")
]
library Image3dlib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    enum      Image3dAPIVersion;
    interface IImage3dFileLoader;
};
